spring:
  application:
    name: game
  data:
    redis:
      database: 1
      host: 10.77.38.129
      password: N2kH5lJVJLAHWObs
      port: 6379
  r2dbc:
    url: r2dbc:mysql://10.77.38.129:3306/game?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: N2kH5lJVJLAHWObs
